### ISSUE TITLE
Android support 

### ISSUE THREAD

**Issue by waddles** [grantbeattie/plugin.video.nineau-catchup#2] opened 2014-12-27 08:31 UTC
Addon doesn't seem to work on Kodi 14 on Android. Browsing episodes works but unable to play anything

**Comment by grantbeattie** [comment] 2015-01-05 01:06
I'm guessing this is the same as previous xbmc releases where the Android build doesn't include gnutls support.

Have you tried enabling compatibility mode in the addon settings?

**Comment by grantbeattie** [comment] 2015-09-07 04:48
Confirmed fixed by enabling SSL compatibility for Android and older XBMC releases.

**Closed as completed by grantbeattie** 2015-09-07 04:48 UTC

**Comment by waddles** [comment] 2015-09-08 12:18
Nope, not fixed. See https://gist.github.com/waddles/00e3606d4d133cd8608d

**Comment by grantbeattie** [comment] 2015-09-14 00:46
You're on 15.2 - you don't need the HLS compatibility mode enabled. Disable it and it should work as expected.

(works for me on 15.1)
